easy_admin:
    site_name: 'Books'
    entities:
        Users:
            class: App\Entity\Users
            label: 'Пользователи'
            list:
                title: 'Пользователи'
                fields: ['id', 'email', 'roles']
        Feedback:
            class: App\Entity\Feedback
            label: 'Обратная связь'
            list:
                title: 'Обратная связь'
                fields: ['id', 'firstname', 'lastname', 'email', 'phone', 'message']
        Page:
            class: App\Entity\Page
            label: 'Страницы'
            list:
                title: 'Страницы'
                fields: ['id', 'title', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'Основные' }
                    - { property: visible, label: 'Видимость'}
                    - { type: 'tab' , label: 'Мультиязычный контент' }
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { default_locale: '%locale%', fields: { name: {field_type: 'Symfony\Component\Form\Extension\Core\Type\TextType', label: 'Наименование' }, title: {field_type: 'Symfony\Component\Form\Extension\Core\Type\TextType', label: 'Заголовок' }, content: {field_type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', label: 'Контент'}}}}
                    - { type: 'tab' , label: 'Мета' }
                    - { property: meta_keywords, label: 'Мета Ключевые слова'}
                    - { property: meta_description, label: 'Мета Описание'}
                    - { type: 'tab', label: 'Адреса' }
                    - { property: 'pageUrls', type_options: { block_name: 'page_urls', by_reference: false }}
        Block:
            class: App\Entity\Block
            label: 'Блоки'
            list:
                title: 'Блоки'
                fields: ['id', 'title', 'name', 'visible']
            form:
                fields:
                    - { type: 'tab' , label: 'Основные' }
                    - { property: visible, label: 'Видимость' }
                    - { property: name, label: 'Наименование' }
                    - { type: 'tab' , label: 'Мультиязычный контент' }
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: {default_locale: '%locale%', fields: { title: {field_type: 'Symfony\Component\Form\Extension\Core\Type\TextType', label: 'Заголовок' }, content: {field_type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', label: 'Контент' }}}}
        Project:
            class: App\Entity\Project
            label: 'Проекты'
            list:
                title: 'Проекты'
                fields:
                    - { property: id, label: 'ID' }
                    - { property: title, label: 'Заголовок' }
                    - { property: main_image, template: 'admin/renderers/image.html.twig', label: 'Основное изображение' }
                    - { property: middle_image, template: 'admin/renderers/image.html.twig', label: 'Вспомогательное изображение' }
                    - { property: link, label: 'Книга', template: 'admin/renderers/file.html.twig' }
                    - { property: url, label: 'Адрес', template: 'admin/renderers/project_url.html.twig' }
            form:
                fields:
                    - { type: 'tab' , label: 'Основные' }
                    - { property: translations, label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: {default_locale: '%locale%', fields: { title: {field_type: 'Symfony\Component\Form\Extension\Core\Type\TextType', label: 'Заголовок' }, description: {field_type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', label: 'Описание' }, short_description: {field_type: 'FOS\CKEditorBundle\Form\Type\CKEditorType', label: 'Краткое описание' }}}}
                    - { type: 'tab' , label: 'Изображения' }
                    - { property: main_image, label: 'Основное изображение', type_options: { block_name: 'image' }}
                    - { property: middle_image, label: 'Среднее изображение', type_options: { block_name: 'image' }}
                    - { type: 'tab' , label: 'Книга' }
                    - { property: link, label: 'Файл', type_options: { block_name: 'file'}}
                    - { type: 'tab' , label: 'Адреса' }
                    - { property: url, label: 'Адрес проекта' }
        Configuration:
            label: 'Конфигурация сайта'
            class: App\Entity\Configuration
            controller: App\Controller\Admin\ConfigurationController
    design:
        brand_color: 'darkgrey'
        form_theme:
            - '@EasyAdmin/form/bootstrap_3_layout.html.twig'
            - 'admin/form/page_urls.html.twig'
            - 'admin/form/image.html.twig'
            - 'admin/form/file.html.twig'
        assets:
            css:
                - '/css/admin/custom.css'
            js:
                - 'https://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.js'
                - '/bundles/easyadmin/javascript/jq-ui.js'
                - '/bundles/easyadmin/javascript/fileupload.js'
