version: '3.3'
services:
    book_php:
        build: ./docker/php-fpm
        ports:
            - '9000:9000'
        volumes:
            - ${PWD}:/var/www/books
        links:
            - book_db
        networks:
            main:
                aliases:
                    - book_php
    book_nginx:
        build: ./docker/nginx
        ports:
            - '9009:9009'
        depends_on:
            - book_php
        volumes:
            - ${PWD}:/var/www/books
        networks:
            main:
                aliases:
                    - book_nginx

    book_db:
        image: mariadb:latest
        ports:
            - "8181:3306"
        volumes:
            - ./docker/book_db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=books
            - MYSQL_USER=root
        networks:
            main:
                aliases:
                    - book_db
networks:
    main:
