easy_admin_bundle:
  resource: App\Controller\AdminController
  prefix: /admin
  type: annotation

urls:
  path:     /{_locale}/{slug}
  controller: App\Controller\CmsController::page
  requirements:
    _locale: ru|en|de