easy_admin_bundle:
  resource: App\Controller\AdminController
  prefix: /admin
  type: annotation

#urls:
#  path:     /{slug}
#  controller: App\Controller\CmsController::page
#  requirements:
#    slug:  ".*"