easy_admin_bundle:
  resource: App\Controller\AdminController
  prefix: /admin
  type: annotation

Projects:
  resource: App\Controller\ProjectsController
  type: annotation

urls:
  path:     /{slug}
  controller: App\Controller\CmsController::page

app_yandex:
  resource: "Lp/PaymentBundle/Resources/config/routing.yaml"